version: "3.9"

services:
  n8n:
    build: .
    image: n8n-langchain:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n-image-metaboost.onrender.com
      - N8N_PORT=443
      - N8N_PROTOCOL=https
      - NODE_FUNCTION_ALLOW_EXTERNAL=...
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n_data:/data
