services:
  - type: web
    name: n8n-service
    env: docker
    repo: https://github.com/KyleSeaford/n8n_image_metaboost.git
    branch: main
    plan: pro
    envVars:
      ...
      - key: N8N_HOST
        value: n8n-image-metaboost.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 443
      - key: WEBHOOK_URL
        value: https://n8n-image-metaboost.onrender.com
databases:
  - name: n8n-db
    plan: Basic-256mb
